import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/UI/header/Header";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pl">
      <body className={montserrat.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
