import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/UI/header/Header";
// import { AuthProvider } from "./AuthContext";
import { getServerSession } from "next-auth";
import SessionProvider from "../components/SessionProvider";
import Footer from "@/components/UI/footer/Footer";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="pl">
      <body className={montserrat.className}>
        <SessionProvider session={session}>
          <Header />
          {children}
          <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}
